spring:
  application:
    name: frontend

---
spring:
  profiles: dev
services:
  user-profile-api: 'http://localhost:8082'
  manga-api: 'http://localhost:8081'

---
spring:
  profiles: kubernetes
services:
  user-profile-api: 'http://user-profile-api'
  manga-api: 'http://manga-api'