spring:
  application:
    name: authentication-api
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
---
spring:
  profiles: dev
server:
  port: 8083
---
spring:
  profiles: kubernetes