spring:
  application:
    name: manga-api
  data:
    mongodb:
      uri: mongodb://localhost:27017/suupaa-manga
---
spring:
  profiles: dev
services:
  user-profile-api: 'http://localhost:8082'

---
spring:
  profiles: kubernetes
services:
  user-profile-api: 'http://user-profile-api'