spring:
  application:
    name: manga-api
  jpa:
    show-sql: "true"
    hibernate.ddl-auto: none
  datasource:
    url: "jdbc:postgresql://host.docker.internal:5432/postgres"
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  liquibase:
    change-log: "classpath:/db/changelog-master.xml"

---
spring:
  profiles: dev
services:
  user-profile-api: 'http://localhost:8082'

---
spring:
  profiles: kubernetes
services:
  user-profile-api: 'http://user-profile-api'