spring:
  application:
    name: manga-api
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
kafka:
  topic:
    manga-rate: manga-rate
    manga-view: manga-view
---
spring:
  profiles: dev
  data:
    mongodb:
      uri: mongodb://localhost:27017/suupaa-manga
  kafka:
    bootstrap-servers: localhost:9092
server:
  port: 8081
---
spring:
  profiles: kubernetes