apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: suupaa-manga-be
build:
  artifacts:
    - image: suupaa-manga/manga
      jib:
        project: org.suupaa.manga:manga
    - image: suupaa-manga/user-profile
      jib:
        project: org.suupaa.manga:user-profile
    - image: suupaa-manga/frontend
      jib:
        project: org.suupaa.manga:frontend
deploy:
  kubectl:
    manifests:
      - _infra/kubernetes/db-secrets.yml
      - _infra/kubernetes/manga-deployment.yml
      - _infra/kubernetes/user-profile-deployment.yml