spring:
  application:
    name: gateway-api
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
---
server:
  port: 8080
spring:
  profiles: dev
  cloud:
    gateway:
      routes:
        - id: manga-api
          uri: http://localhost:8081
          predicates:
            - Path=/manga-api/{segment}
          filters:
            - SetPath=/{segment}
            - AuthRelay
        - id: recommendation-api
          uri: http://localhost:8082
          predicates:
            - Path=/recommendation-api/{segment}
          filters:
            - SetPath=/{segment}
            - AuthRelay
        - id: user-profile-api
          uri: http://localhost:8084
          predicates:
            - Path=/user-profile-api/{segment}
          filters:
            - SetPath=/{segment}
            - AuthRelay
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET,POST,PUT,HEAD,PATCH,DELETE
---
spring:
  profiles: kubernetes
  cloud:
    gateway:
      routes:
        - id: all-routes
          uri: http://service:80
          predicates:
            - Path=/{service}/**
          filters:
            - RouteToHost
            - StripPrefix=1
            - AuthRelay