apiVersion: apps/v1
kind: Deployment
metadata:
  name: manga-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manga-api
  template:
    metadata:
      labels:
        app: manga-api
    spec:
      containers:
        - name: manga
          image: suupaa-manga/manga
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes
---
apiVersion: v1
kind: Service
metadata:
  name: manga-api
spec:
  type: NodePort
  selector:
    app: manga-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 32001