apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-profile-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-profile-api
  template:
    metadata:
      labels:
        app: user-profile-api
    spec:
      containers:
        - name: user-profile-api
          image: suupaa-manga/user-profile
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: user-profile-api
spec:
  type: NodePort
  selector:
    app: user-profile-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32000
